sudo: false
language: node_js
node_js:
- 0.12
- 4
- 5
- 6
env:
- BROWSER_TESTS="no"
matrix:
 include:
 - node_js: 6.8
   env: BROWSER_TESTS="yes"
script:
- if [ "$BROWSER_TESTS" == "no" ]; then bash ./bin/travis.sh; fi
- if [ "$BROWSER_TESTS" == "yes" ]; then npm run test-browser-ci; fi